name: Test Credentials

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R dependencies
        run: |
          # Instalar pacotes um por um para garantir que todos sejam instalados corretamente
          install.packages("basedosdados")
          install.packages("rsconnect")
          
          # Verificar se os pacotes foram instalados corretamente
          installed_packages <- installed.packages()[,"Package"]
          required_packages <- c("basedosdados", "rsconnect")
          
          missing_packages <- required_packages[!required_packages %in% installed_packages]
          
          if (length(missing_packages) > 0) {
            stop(paste("Os seguintes pacotes não foram instalados:", paste(missing_packages, collapse=", ")))
          } else {
            cat("Todos os pacotes foram instalados com sucesso!\n")
          }
        shell: Rscript {0}
      
      - name: Test credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          # Criar arquivo temporário para as credenciais do Google Cloud
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > google-credentials.json
          
          # Executar o script de teste específico para GitHub Actions
          source(".github/scripts/test-credentials.R")
        shell: Rscript {0}
