name: Deploy‑Shiny‑App
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: observatorio-portuario

    steps:
      # 1. Código‑fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Ambiente R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3. Restaurar (e compilar) dependências com renv
      - name: Restore renv cache
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      # 4. Instalar pacotes adicionais não capturados no lockfile
      - name: Install extra packages
        run: |
          Rscript -e 'install.packages(c("basedosdados", "rsconnect", "tidyverse"))'

      # 5. Gravar chave GCP e definir GOOGLE_APPLICATION_CREDENTIALS
      - name: Configure Google Cloud credentials
        shell: bash
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > "${HOME}/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json" >> "$GITHUB_ENV"

      # 6. Testar credenciais
      - name: Test credentials
        run: Rscript test-credentials.R

      # 7. Deploy para shinyapps.io
      - name: Deploy application
        run: Rscript github-action-deploy.R
        env:
          SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
