name: Deploy‑Shiny‑App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: observatorio-portuario   # usado pelo basedosdados

    steps:
      # 1. Código‑fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Ambiente R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Restore renv cache
        uses: r-lib/actions/setup-renv@v2

      # 3. Dependências do sistema (apt) e pacotes R não capturados em renv
      - name: Install extra packages
        run: |
          Rscript -e 'install.packages(c("basedosdados", "rsconnect", "tidyverse"))'

      # 4. Gravar chave e exportar variável de ambiente
      - name: Configure Google Cloud credentials
        shell: bash
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > "${HOME}/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json" >> "$GITHUB_ENV"

      # 5. Teste local das credenciais
      - name: Test credentials
        run: Rscript test-credentials.R

      # 6. Deploy para shinyapps.io
      - name: Deploy application
        run: Rscript github-action-deploy.R
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
