name: Update Data and Deploy

on:
  # Execução programada mensalmente (dia 29 às 03:00 UTC)
  schedule:
    - cron: '0 3 29 * *'
  
  # Permitir execução manual quando necessário
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R dependencies
        run: |
          install.packages(c("tidyverse", "lubridate", "basedosdados", "rsconnect", "shiny", "shinydashboard", "highcharter", "jsonlite", "RColorBrewer", "DT"))
        shell: Rscript {0}
      
      - name: Configure Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > gc-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=gc-key.json" >> $GITHUB_ENV
      
      - name: Update data
        run: |
          Rscript caged-baixar-dados.R
      
      - name: Commit and push updated data
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/df.rds
          git commit -m "Update data (automated)" || echo "No changes to commit"
          git push
      
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='observatorioportuario', token='${{ secrets.SHINYAPPS_TOKEN }}', secret='${{ secrets.SHINYAPPS_SECRET }}')"
          Rscript -e "rsconnect::deployApp(appName='painel_caged_portuario', account='observatorioportuario')"
