name: Update Data and Deploy

on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    - cron: '0 12 29 * *'  # Executa às 12:00 UTC no dia 29 de cada mês

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # Mantenha a versão do R consistente com seu renv.lock
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      # REMOVIDO o passo antigo "Install R dependencies" que usava install.packages

      # ADICIONADO: Restaurar pacotes R usando renv
      - name: Restore R environment from renv.lock
        uses: r-lib/actions/setup-renv@v2 
        # Esta action irá executar renv::restore() para instalar os pacotes
        # exatamente como definidos no seu arquivo renv.lock e também
        # configurará cache para acelerar execuções futuras.
        
      - name: Test credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credencial_google.json
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          # Execute the test script
          Rscript .github/scripts/test-credentials.R
          
      - name: Update data
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credencial_google.json
        run: |
          # Execute the script
          Rscript .github/scripts/update-data.R
          
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          # Execute the deploy script
          Rscript .github/scripts/deploy-app.R 
          # Certifique-se que este script (.github/scripts/deploy-app.R)
          # apenas faz o deploy e não tenta instalar pacotes ou fazer snapshot.
          
      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          # Usa '|| true' para não falhar se não houver mudanças para commitar
          git commit -m "Atualização automática dos dados [skip ci]" || true 
          git push