name: Update Data and Deploy

on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    - cron: '0 12 29 * *'  # Executa às 12:00 UTC no dia 29 de cada mês

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R dependencies
        run: |
          # Instalar pacotes um por um para garantir que todos sejam instalados corretamente
          install.packages("shiny")
          install.packages("shinydashboard")
          install.packages("tidyr")
          install.packages("dplyr")
          install.packages("ggplot2")
          install.packages("readr")
          install.packages("purrr")
          install.packages("tibble")
          install.packages("stringr")
          install.packages("forcats")
          install.packages("highcharter")
          install.packages("jsonlite")
          install.packages("RColorBrewer")
          install.packages("DT")
          install.packages("basedosdados")
          install.packages("rsconnect")
          install.packages("lubridate")
          
          # Verificar se os pacotes foram instalados corretamente
          installed_packages <- installed.packages()[,"Package"]
          required_packages <- c("shiny", "shinydashboard", "tidyr", "dplyr", "ggplot2", 
                                "readr", "purrr", "tibble", "stringr", "forcats", 
                                "highcharter", "jsonlite", "RColorBrewer", "DT", 
                                "basedosdados", "rsconnect", "lubridate")
          
          missing_packages <- required_packages[!required_packages %in% installed_packages]
          
          if (length(missing_packages) > 0) {
            stop(paste("Os seguintes pacotes não foram instalados:", paste(missing_packages, collapse=", ")))
          } else {
            cat("Todos os pacotes foram instalados com sucesso!\n")
          }
        shell: Rscript {0}
      
      - name: Test credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          # Write the Google Cloud credentials to a file
          printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > google-credentials.json
          
          # Execute the test script
          Rscript .github/scripts/test-credentials.R
      
      - name: Update data
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          # Write the Google Cloud credentials to a file
          printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > google-credentials.json
          
          # Execute the script
          Rscript .github/scripts/update-data.R
      
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          # Execute the deploy script
          Rscript .github/scripts/deploy-app.R
      
      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Atualização automática dos dados [skip ci]" || echo "No changes to commit"
          git push
